apiVersion: v1
kind: Pod
metadata:
  name: poccicd
  labels:
    role: prod
spec:
  containers:
    - name: poccicd
      image: localhost:32000/poccicd
      env:
        - name: TZ
          value: America/Santiago
      ports:
        - name: web
          containerPort: 9000
          protocol: TCP
