apiVersion: v1
kind: Pod
metadata:
  name: timezone
spec:
  containers:
    - name: timezone
      image: registry-vpc.cn-beijing.aliyuncs.com/eci_open/busybox:1.30
      command: ["sleep", "10000"]
      volumeMounts:
        - name: tz
          mountPath: /etc/localtime
          subPath: Shanghai
  volumes:
    - name: tz
      configMap:
        name: tz
  nodeSelector:
    type: virtual-kubelet
  tolerations:
    - key: virtual-kubelet.io/provider
      operator: Exists
